#!/bin/bash
# Filename...: rhel6-ad-winbind.sh
# Description: Configures AD authentication on RHEL6 via Winbind (idmap_ad)
# Chris Elliott -- https://github.com/c-elliott

# Settings
KDC="DOMAINCONTROLLER.EXAMPLE.DOMAIN.COM"
REALM="EXAMPLE.DOMAIN.COM"
WORKGROUP="EXAMPLE"
TESTUSER="testuser"
DOMAINADMIN="Administrator"

        ############# DO NOT EDIT BELOW THIS LINE #############

# Continue only if we can ping our KDC
ping -q -c5 $KDC > /dev/null
if [ $? -eq 0 ]; then

  # Backup configuration before we begin
  /bin/cp -rf /etc/krb5.conf /etc/krb5.conf.bak
  /bin/cp -rf  /etc/samba/smb.conf /etc/samba/smb.conf.bak
  /bin/cp -rf  /etc/sysconfig/authconfig /etc/sysconfig/authconfig.bak

  # Clean input data before insertion into config files
  KDC_LC=`echo $KDC | tr '[:upper:]' '[:lower:]'`
  KDC_UC=`echo $KDC | tr '[:lower:]' '[:upper:]'`
  REALM_LC=`echo $REALM | tr '[:upper:]' '[:lower:]'`
  REALM_UC=`echo $REALM | tr '[:lower:]' '[:upper:]'`
  WORKGROUP_UC=`echo $WORKGROUP | tr '[:lower:]' '[:upper:]'`

  # Ensure we have a default /etc/krb5.conf
  rm -f /etc/krb5.conf
  yum -y reinstall krb5-libs

  # Install all prerequisites
  yum -y install samba samba-common samba-winbind krb5-workstation oddjob ntp

  # Configure ntp
  sed -i '/^server/ s/^/#/' /etc/ntp.conf
  echo "server $KDC" >> /etc/ntp.conf
  ntpdate $KDC
  service ntpd start
  chkconfig ntpd on

  # Configure oddjobd to preserve selinux context
  service oddjobd start
  chkconfig oddjobd on

  # Configure kerberos
  sed -i 's/EXAMPLE.COM/'$REALM_UC'/g' /etc/krb5.conf
  sed -i 's/kerberos.example.com/'$KDC_LC'/g' /etc/krb5.conf
  sed -i 's/example.com/'$REALM_LC'/g' /etc/krb5.conf

  # Test kerberos
  kdestroy
  kinit $TESTUSER
  if [ `klist | grep -c renew` -eq 0 ]; then
    echo -e "\n ERROR. Kerberos TGT not recieved. Check configuration /etc/krb5.conf \n"
    exit 0
  fi

  # Configure samba and winbind
  cat <<< "
    # Generated by rhel6-ad-winbind.sh (`date`)
    # ------------------------------------------------------------------------

    [global]
     workgroup = $WORKGROUP_UC
     password server = $KDC_UC
     realm = $REALM_UC
     security = ads
     idmap config * : range = 16777216-33554431
     idmap uid = 20000-29999
     idmap gid = 20000-29999
     template shell = /bin/bash
     winbind use default domain = yes
     winbind offline logon = false
     winbind enum users = no
     winbind enum groups = no
     winbind separator = +
     winbind nested groups = yes

    # ------------------------------------------------------------------------
  " > /etc/samba/smb.conf

  # Start winbind
  service winbind start
  chkconfig winbind on

  # Test winbind
  if [ `service winbind status | grep -c running` -eq 0 ]; then
    echo -e"\n ERROR. Winbind service not running. \n"
    exit 0
  fi

  # Join domain
  net join -S $KDC -U $DOMAINADMIN

  # Test domain
  if [ `net ads testjoin | grep -c OK` -eq 0 ]; then
    echo -e"\n ERROR. Active directory join failed. \n"
    exit 0
  fi
 
  # Enable winbind and homedir creation via authconfig
  authconfig --enablemkhomedir --enablewinbind --enablewinbindauth --update

  # Create domain home directory with selinux context
  mkdir /home/${WORKGROUP_UC}
  restorecon -R /home

  # Completion message
  clear
  echo "Configuration of Active Directory Authentication has been completed."
  echo
  echo "You should test active directory:"
  echo "wbinfo -u or wbinfo -g to dislpay users/groups."
  echo
  echo "If all is OK, you should be able to login as a domain user."
  echo

else

  echo "STOPPED. Unable to ping KDC: $KDC"
  echo "Check DNS configuration."

fi
